---

os: linux
dist: bionic
language: python
services: docker

env:
  global:
    - ROLE_NAME: nginx-revproxy
  jobs:
    # - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule[docker] yamllint ansible ansible-lint docker

script:
  # Run tests.
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
